name: Build Toolchain with webos_tv_defconfig

# Trigger this workflow manually
on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Target platform for the build'
        required: true
        default: 'webos_tv_defconfig'
        type: string

env:
        TOOLCHAIN_TARGET: webos
        DEFCONFIG: webos_tv_defconfig
        BR2_CCACHE_DIR: ${HOME}/.buildroot-ccache-webos
        
jobs:
  build_toolchain:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up dependencies (e.g., install necessary tools)
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git wget python3 python3-pip

      # Step 3: Download and install Buildroot (if not already available)
      - name: Clone Buildroot
        run: |
          git clone --depth=1 https://github.com/buildroot/buildroot.git
          cd buildroot
          git checkout master

      # Step 4: Set the Buildroot configuration (webos_tv_defconfig)
      - name: Set Buildroot config to webos_tv_defconfig
        run: |
          cd buildroot
          make ${DEFCONFIG}

      # Step 5: Build the toolchain
      - name: Build the toolchain
        run: |
          cd buildroot
          make sdk

      # Step 6: Archive the toolchain
      - name: Archive toolchain
        uses: actions/upload-artifact@v4
        with:
          name: webos_toolchain
          path: buildrootoutput/images/*_sdk-buildroot.tar.gz

      # Step 7: Optional - Clean up after the build
      - name: Clean up build directory
        run: |
          rm -rf buildroot
